apiVersion: batch/v1
kind: CronJob
metadata:
  name: grpcgoonchclient-roundrobin-cronjob
  labels:
    app: grpcgoonchclient-roundrobin
spec:
  schedule: "0/8 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: grpcgoonchclient-roundrobin
    spec:
      template:
        spec:
          containers:
          - name: grpcgoonchclient-roundrobin
            image: thaigoonch/grpcgoonchclient-roundrobin:1.0
            imagePullPolicy: IfNotPresent
            env:
            - name: LOG_LEVEL
              value: "DEBUG"
          restartPolicy: Never
          nodeSelector:
            goonchrole: "nonserver"